import { Offer } from "@/types"

export const INITIAL_OFFERS: Offer[] = [
    // TEST OFFER 1: Full and waiting for credentials (for sponsor to test submission)
    {
        id: 'test-full-pending',
        service: 'Netflix',
        title: 'Netflix Premium - Ready for Credentials',
        description: 'Test offer that is full and waiting for sponsor to submit credentials.',
        totalSeats: 3,
        takenSeats: 3,
        price: 5.99,
        currency: 'USD',
        period: 'mo',
        sponsorId: 'current-user',
        sponsorName: 'You',
        sponsorAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=You',
        status: 'FULL_PENDING_CREDENTIAL',
        createdAt: new Date(Date.now() - 86400000 * 2),
        credentialDeadline: new Date(Date.now() + 86400000 * 0.5),
        members: ['test-member1', 'test-member2', 'test-member3'],
        tags: ['4K UHD', 'Test - Submit Credentials']
    },
    // TEST OFFER 2: Credentials submitted 3+ days ago (ready to withdraw)
    {
        id: 'test-releasable',
        service: 'Spotify',
        title: 'Spotify Premium - Ready to Withdraw',
        description: 'Test offer with credentials submitted 4 days ago. Ready for fund withdrawal.',
        totalSeats: 4,
        takenSeats: 4,
        price: 3.99,
        currency: 'USD',
        period: 'mo',
        sponsorId: 'current-user',
        sponsorName: 'You',
        sponsorAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=You',
        status: 'RELEASABLE',
        createdAt: new Date(Date.now() - 86400000 * 10),
        credentialDeadline: new Date(Date.now() - 86400000 * 9),
        credentials: {
            username: 'spotify_test@email.com',
            password: 'TestPassword123',
            submittedAt: new Date(Date.now() - 86400000 * 4),
            unlockAt: new Date(Date.now() - 86400000 * 1) // 1 day ago (past the 3-day window)
        },
        members: ['test-member1', 'test-member2', 'test-member3', 'test-member4'],
        tags: ['Premium', 'Test - Withdraw Funds']
    }, {
        id: '1',
        service: 'Netflix',
        title: 'Netflix Premium 4K',
        description: 'Looking for 2 people to join my long-term family plan. 4K UHD supported.',
        totalSeats: 4,
        takenSeats: 2,
        price: 4.99,
        currency: 'USD',
        period: 'mo',
        sponsorId: 'sponsor1',
        sponsorName: 'Sarah J.',
        sponsorAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Sarah',
        status: 'LISTED',
        createdAt: new Date(Date.now() - 86400000 * 5),
        credentialDeadline: new Date(Date.now() - 86400000 * 4),
        members: ['member1', 'member2'],
        tags: ['4K UHD', 'Long-term']
    }, {
        id: '2',
        service: 'Spotify',
        title: 'Spotify Family Plan',
        description: 'Music lovers united! Join our family plan for the best rates.',
        totalSeats: 6,
        takenSeats: 6,
        price: 2.99,
        currency: 'USD',
        period: 'mo',
        sponsorId: 'sponsor2',
        sponsorName: 'Mike R.',
        sponsorAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Mike',
        status: 'CREDENTIAL_SUBMITTED',
        createdAt: new Date(Date.now() - 86400000 * 10),
        credentialDeadline: new Date(Date.now() - 86400000 * 9),
        credentials: {
            username: 'spotify_family@email.com',
            password: 'SecurePass123',
            submittedAt: new Date(Date.now() - 86400000 * 2),
            unlockAt: new Date(Date.now() + 86400000)
        },
        members: ['member1', 'member3', 'member4', 'member5', 'member6', 'member7'],
        tags: ['No Ads', 'Offline']
    },
    // Test offer for login - Netflix with credentials ready
    {
        id: 'test-netflix',
        service: 'Netflix',
        title: 'Netflix Standard HD - Test Login',
        description: 'Test offer with credentials ready for login verification.',
        totalSeats: 4,
        takenSeats: 4,
        price: 3.99,
        currency: 'USD',
        period: 'mo',
        sponsorId: 'sponsor-test',
        sponsorName: 'Test Sponsor',
        sponsorAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=TestSponsor',
        status: 'CREDENTIAL_SUBMITTED',
        createdAt: new Date(Date.now() - 86400000 * 7),
        credentialDeadline: new Date(Date.now() - 86400000 * 6),
        credentials: {
            username: 'test_netflix@email.com',
            password: 'TestPass123',
            submittedAt: new Date(Date.now() - 86400000 * 4),
            unlockAt: new Date(Date.now() + 86400000 * 2)
        },
        members: ['member1', 'test-member1', 'test-member2', 'test-member3'],
        tags: ['HD', 'Test Account']
    }, {
        id: '3',
        service: 'YouTube',
        title: 'YouTube Premium',
        description: 'Ad-free YouTube and Music. Reliable monthly payments required.',
        totalSeats: 5,
        takenSeats: 5,
        price: 3.5,
        currency: 'USD',
        period: 'mo',
        sponsorId: 'sponsor3',
        sponsorName: 'Alex Chen',
        sponsorAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Alex',
        status: 'FULL_PENDING_CREDENTIAL',
        createdAt: new Date(Date.now() - 86400000 * 1),
        credentialDeadline: new Date(Date.now() + 86400000 * 0.5),
        members: ['member1', 'member8', 'member9', 'member10', 'member11'],
        tags: ['Ad-free', 'Music']
    }, {
        id: '4',
        service: 'Disney+',
        title: 'Disney+ Bundle',
        description: 'Includes Hulu and ESPN+. Great value for entertainment lovers.',
        totalSeats: 4,
        takenSeats: 1,
        price: 4.5,
        currency: 'USD',
        period: 'mo',
        sponsorId: 'sponsor4',
        sponsorName: 'Emily W.',
        sponsorAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Emily',
        status: 'LISTED',
        createdAt: new Date(Date.now() - 86400000 * 3),
        credentialDeadline: new Date(Date.now() - 86400000 * 2),
        members: ['member12'],
        tags: ['Bundle', 'Hulu']
    }, {
        id: '5',
        service: 'Apple One',
        title: 'Apple One Premier',
        description: 'iCloud+, Music, TV+, Arcade, News+, and Fitness+. Full package.',
        totalSeats: 6,
        takenSeats: 6,
        price: 6.99,
        currency: 'USD',
        period: 'mo',
        sponsorId: 'sponsor5',
        sponsorName: 'David K.',
        sponsorAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=David',
        status: 'RELEASABLE',
        createdAt: new Date(Date.now() - 86400000 * 15),
        credentialDeadline: new Date(Date.now() - 86400000 * 14),
        credentials: {
            username: 'apple_family@icloud.com',
            password: 'AppleSecure456',
            submittedAt: new Date(Date.now() - 86400000 * 5),
            unlockAt: new Date(Date.now() - 86400000 * 2)
        },
        members: ['member1', 'member13', 'member14', 'member15', 'member16', 'member17'],
        tags: ['2TB iCloud', 'All Apps']
    }, {
        id: '6',
        service: 'HBO Max',
        title: 'HBO Max Ad-Free',
        description: 'Watch the latest hits in 4K. Sharing my annual subscription.',
        totalSeats: 3,
        takenSeats: 0,
        price: 5.99,
        currency: 'USD',
        period: 'mo',
        sponsorId: 'sponsor6',
        sponsorName: 'Jessica L.',
        sponsorAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Jessica',
        status: 'LISTED',
        createdAt: new Date(Date.now() - 86400000 * 2),
        credentialDeadline: new Date(Date.now() - 86400000 * 1),
        members: [],
        tags: ['4K', 'Annual']
    }
];
